# Generated by Django 2.2.6 on 2019-11-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_id', models.IntegerField()),
                ('username', models.TextField()),
                ('title', models.TextField()),
                ('url', models.TextField()),
                ('score', models.IntegerField()),
                ('sentiment', models.FloatField()),
            ],
        ),
    ]
